//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebScraping.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--
        ///You know you could be getting paid to poke around in our code?
        ///We&apos;re hiring designers and developers to work in Amsterdam:
        ///https://careers.booking.com/
        ///--&gt;
        ///&lt;!-- wdot-802 --&gt;
        ///&lt;script type=&quot;text/javascript&quot; nonce=&quot;gnYeEEDxU0gcZHj&quot; src=&quot;https://cdn.cookielaw.org/consent/3ea94870-d4b1-483a-b1d2-faf1d982bb31/OtAutoBlock.js&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot; nonce=&quot;gnYeEEDxU0gcZHj&quot; src=&quot;https://cf.bstatic.com/libs/privacy-consent/1.0.1/customer/cookie-banner.min.js&quot; data-domain [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlDocument {
            get {
                return ResourceManager.GetString("HtmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;HotelName&quot;: &quot;Hotel Bristol Berlin&quot;,
        ///  &quot;Address&quot;: &quot;Kurf\u00FCrstendamm 27, Charlottenburg-Wilmersdorf, 10719 Berlin, Germany&quot;,
        ///  &quot;Classification&quot;: &quot;5 out of 5&quot;,
        ///  &quot;ReviewPoints&quot;: 8.3,
        ///  &quot;NumberOfReviews&quot;: 3610,
        ///  &quot;Description&quot;: &quot; One of our top picks in Berlin.  Hotel Bristol Berlin is a vibrant, legendary hotel located directly on the famous Kurf\u00FCrstendamm boulevard, opening its doors in 1952. The hotel offers complimentary WiFi throughout the premises and there is a nearby underground parki [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonString {
            get {
                return ResourceManager.GetString("JsonString", resourceCulture);
            }
        }
    }
}
